sudo: required
services:
  - docker

before_install:
  - docker build -t bel-mont/docker-test -f Dockerfile.dev .

script: 
  - docker run -e CI=true bel-mont/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-964071509333"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY